# Generated by Django 4.2.7 on 2023-12-13 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('nom_ingredient', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('nom_recette', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('temps_preparation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('temps_cuisson', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(upload_to='photo_plat/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('texte_instruction', models.TextField()),
                ('nom_ingredient', models.ManyToManyField(to='EasyCook.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('nom_service', models.CharField(choices=[('Entrée', 'Entrée'), ('Plat', 'Plat'), ('Dessert', 'Dessert')], max_length=10)),
                ('origine', models.CharField(choices=[('Afrique du Sud', 'Afrique du Sud'), ('Algérie', 'Algérie'), ('Allemagne', 'Allemagne'), ('Angleterre', 'Angleterre'), ('Argentine', 'Argentine'), ('Australie', 'Australie'), ('Autriche', 'Autriche'), ('Belgique', 'Belgique'), ('Brésil', 'Brésil'), ('Canada', 'Canada'), ('Chili', 'Chili'), ('Chine', 'Chine'), ('Colombie', 'Colombie'), ('Corée du Sud', 'Corée du Sud'), ('Cuba', 'Cuba'), ('Danemark', 'Danemark'), ('Égypte', 'Égypte'), ('Espagne', 'Espagne'), ('États-Unis', 'États-Unis'), ('Finlande', 'Finlande'), ('France', 'France'), ('Grèce', 'Grèce'), ('Hongrie', 'Hongrie'), ('Inde', 'Inde'), ('Indonésie', 'Indonésie'), ('Iran', 'Iran'), ('Irlande', 'Irlande'), ('Italie', 'Italie'), ('Japon', 'Japon'), ('Liban', 'Liban'), ('Malaisie', 'Malaisie'), ('Maroc', 'Maroc'), ('Mexique', 'Mexique'), ('Norvège', 'Norvège'), ('Pays-Bas', 'Pays-Bas'), ('Pérou', 'Pérou'), ('Pologne', 'Pologne'), ('Portugal', 'Portugal'), ('République Tchèque', 'République Tchèque'), ('Roumanie', 'Roumanie'), ('Russie', 'Russie'), ('Sénégal', 'Sénégal'), ('Suède', 'Suède'), ('Suisse', 'Suisse'), ('Tunisie', 'Tunisie'), ('Turquie', 'Turquie'), ('Ukraine', 'Ukraine'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam')], max_length=20)),
                ('nom_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_recette', to='EasyCook.recette', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=200)),
                ('note', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('nom_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyCook.recette')),
            ],
        ),
        migrations.CreateModel(
            name='RecetteIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyCook.ingredients')),
                ('nom_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyCook.recette')),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recette', to='EasyCook.service'),
        ),
        migrations.CreateModel(
            name='Photo_plat',
            fields=[
                ('id_photo', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('chemin_photo', models.ImageField(upload_to='media/photo_plat')),
                ('id_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyCook.review')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyCook.service')),
            ],
        ),
        migrations.CreateModel(
            name='Frigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_dispo', models.ManyToManyField(to='EasyCook.ingredients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
