# Generated by Django 5.0 on 2023-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyCook', '0005_sitelanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='origine',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Afrique du Sud', 'Afrique du Sud'), ('Algérie', 'Algérie'), ('Allemagne', 'Allemagne'), ('Angleterre', 'Angleterre'), ('Argentine', 'Argentine'), ('Australie', 'Australie'), ('Autriche', 'Autriche'), ('Belgique', 'Belgique'), ('Brésil', 'Brésil'), ('Canada', 'Canada'), ('Chili', 'Chili'), ('Chine', 'Chine'), ('Colombie', 'Colombie'), ('Corée du Sud', 'Corée du Sud'), ('Cuba', 'Cuba'), ('Danemark', 'Danemark'), ('Égypte', 'Égypte'), ('Espagne', 'Espagne'), ('États-Unis', 'États-Unis'), ('Finlande', 'Finlande'), ('France', 'France'), ('Grèce', 'Grèce'), ('Hongrie', 'Hongrie'), ('Inde', 'Inde'), ('Indonésie', 'Indonésie'), ('Iran', 'Iran'), ('Irlande', 'Irlande'), ('Italie', 'Italie'), ('Japon', 'Japon'), ('Liban', 'Liban'), ('Malaisie', 'Malaisie'), ('Maroc', 'Maroc'), ('Mexique', 'Mexique'), ('Norvège', 'Norvège'), ('Pays-Bas', 'Pays-Bas'), ('Pérou', 'Pérou'), ('Pologne', 'Pologne'), ('Portugal', 'Portugal'), ('République Tchèque', 'République Tchèque'), ('Roumanie', 'Roumanie'), ('Russie', 'Russie'), ('Sénégal', 'Sénégal'), ('Suède', 'Suède'), ('Suisse', 'Suisse'), ('Tunisie', 'Tunisie'), ('Turquie', 'Turquie'), ('Ukraine', 'Ukraine'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam')], max_length=20),
        ),
    ]
